### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by User-Reid**
Added additional CSS like hover as well as radius to cards. Also added some margin to the header.

### CODE REVIEW

**Comment by ricanlonghorn23** [comment]
Reviewed code and developer added radius and added second row of card and changed icon.

**Review by ricanlonghorn23 — APPROVED** [review]
All code for this pull request functions correctly

**Review by sd8295642 — CHANGES_REQUESTED** [review]
Comment

**Review by sd8295642 — APPROVED** [review]

**Review by GuillerSaenz — APPROVED** [review]
very good! again.

**Pull request merged**
